#!/usr/bin/env python3


import lib.crypto
import client.network
import client.storage
import sys


def terminal_exit():
    print("terminal stopping")
    sys.exit(0)

def main():
    # init storage
    storage = client.storage.Client()
    storage.init_certificate()
    storage.init_cryptography()
    # init network
    network = client.network.Client()

    # start terminal interface
    print("#### Bitcoin Core Handler terminal ####")
    server_addr = input("\ninsert server ip >> ")
    server_port = int(input("\ninsert server port >>"))

    print(f"connecting to {server_addr}")
    network.remoteHost = server_addr
    network.remotePort = server_port
    # connecting to server
    network.connectToServer()
    # handshake
    if network.isConnected:
        network.make_handshake(storage.certificate)
    else:
        print(f"couldn't connect to server {server_addr}")
        terminal_exit()
    
    if not network.handshake_done:
        print(f"handshake to server {server_addr} refused")
        terminal_exit()
    
    print(f"connection to {server_addr} established and handshake [{network.handshake_done}]")

    network.set_waiting_mode()
    # init network crypto
    network.init_crypto()

    # open terminal calls interface
    print("Insert a call request or digit 'exit' to close the terminal")
    while network.isConnected:
        request = str(input("\n>> ")).lower()
        result = None
        if request == 'exit': terminal_exit()
        if network.write(request):
            result = network.read()
        if bool(result):
            result = json.loads(result)
            for key, value in result:
                print(f"{key}: {value}")

if __name__ == '__main__':
    main()