#!/usr/bin/env python3

#############################################################################
# Copyright [2023] [R0BM01@pm.me]                                           #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
# http://www.apache.org/licenses/LICENSE-2.0                                #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

import time, sys
from multiprocessing import current_process
import lib.settings
import lib.logger
import server.storage
import server.server
import server.machine


def certificate_choice(storage):   
    c = input("Type \n'I' to import \n'G' to generate \n'Q' to quit \n>> ").upper()
    if c == 'I': storage.import_certificate(input("Certificate path >> "))
    elif c == 'G': storage.generate_certificate()
    # return storage.check_certificate()


def main():
    storage = server.storage.Storage()
    storage.init_base()

    logger = lib.logger.Logger(storage.dir_tree['debug'], verbose = True)
    logger.add("server: version running", lib.settings.VERSION)

    main_process = current_process()
    main_process.name = "btcCoreHandler"
    
    logger.add("server: process", main_process.name)
    logger.add("server: PID", main_process.pid)

    ## checks if certificate is available
    if not storage.check_certificate():
        logger.add("Certificate must be generated or imported")
        certificate_choice(storage)
    logger.add("storage: certificate is available", storage.verify_certificate())
    storage.init_certificate()
    storage.init_cryptography()

    ## checks directories and files
    logger.add("storage: checking directory tree integrity")
    for directory in storage.dir_tree:
        check = storage.check_exists(storage.dir_tree[directory])
        logger.add(f"storage: [{storage.dir_tree[directory]}]", check)
        if not check: 
            storage.init_dir(storage.dir_tree[directory])
            logger.add(f"storage: dir [{storage.dir_tree[directory]}] created")
    
    for file in storage.file_tree:
        check = storage.check_exists(storage.file_tree[file])
        logger.add(f"storage: [{storage.file_tree[file]}]", check)
        if not check:
            storage.init_file(storage.file_tree[file])
            logger.add(f"storage: file [{storage.file_tree[file]}] created")
    
    
    ## init Server instance
    SERVER = server.server.Server(logger, storage)
    logger.add("server: init time", time.ctime(SERVER.initTime))
    logger.add("server: network ip address", SERVER.NETWORK.settings.host)
    logger.add("server: network open port", SERVER.NETWORK.settings.port)
    logger.add("server: internet is reachable", bool(SERVER.internetIsOn) )
    logger.add("server: bitcoin daemon is running", bool(SERVER.bitcoindRunning) )
    
    ## init Server RPC local controller
    SERVER.localControllerThread.start()


    if SERVER.bitcoindRunning:
        logger.add("server: updating bitcoin cached data")
        SERVER.CACHE.get_bitcoin_info(logger)

        logger.add("bitcoin: client", SERVER.CACHE.bitcoin_info['networkinfo']['subversion'])
        logger.add("bitcoin: uptime", SERVER.CACHE.bitcoin_info['uptime']['uptime'])
        logger.add("bitcoin: chain", SERVER.CACHE.bitcoin_info['blockchaininfo']['chain'])
        logger.add("bitcoin: blocks", SERVER.CACHE.bitcoin_info['blockchaininfo']['blocks'])
        logger.add("bitcoin: peers", SERVER.CACHE.bitcoin_info['networkinfo']['connections'])
    
    if SERVER.bitcoindRunning and SERVER.internetIsOn:
        ## loads known geolocation data from storage
        SERVER.init_geolocation_cache()
        logger.add("geolocation: data loaded from storage", len(SERVER.CACHE.geolocation_index))
        ## sends a single update on geolocation
        SERVER.CACHE.get_geolocation_update(logger)   
        ## init auto update services
        SERVER.init_services()
        time.sleep(1) # waits for services to start

    logger.add("server: starting network")
    SERVER.start_network()

    if SERVER.isOnline: 
        SERVER.start_all()
    else: 
        logger.add("server: socket not working")
        logger.add("server: stopping application and exit")



if __name__ == '__main__':
    main()