#!/usr/bin/env python3


from core import server

def main():
    print("testing btcCoreHandler")
    handler = server.Controller()

    handler.init_network()
    handler.init_services()

    handler.graceful_shutdown()
    print("test done")


if __name__ == "__main__":
    main()