#!/usr/bin/env python3
#############################################################################
# Copyright [2023] [R0BM01@pm.me]                                           #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
# http://www.apache.org/licenses/LICENSE-2.0                                #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

import sys
import subprocess, argparse

from btccorehandler.lib.settings import VERSION
from btccorehandler.lib.network import ClientRPC




parser = argparse.ArgumentParser(prog = "BTC Core Handler", description = "Handles BitcoinCore by remote.")
parser.add_argument("-g", "--gui", help = "starts GUI handler client", action = "store_true")
parser.add_argument("-t", "--terminal", help = "open terminal interface", action = "store_true")
parser.add_argument("-v", "--version", help = "print version and exit", action = "store_true")

subparser = parser.add_subparsers()

server_parser = subparser.add_parser("server", help = "controls server handler")
server_parser.add_argument("-info", help = "gets server information and exit", action = "store_true")
server_parser.add_argument("-new", help = "generates a certificate for a new client", action = "store_true")
server_parser.add_argument("-start", help = "starts server", action = "store_true")
server_parser.add_argument("-stop", help = "stops server", action = "store_true")

args = parser.parse_args()

clientRPC = ClientRPC()
server_on = clientRPC.is_server_running()

server_cmd = False #any([args.info, args.start, args.stop])


"""if not args.version and not server_cmd:
    # runs the gui
    print("runs the GUI")"""
if args.version:
    print(f"Running btcCoreHandler {VERSION}")
elif args.terminal:
    subprocess.Popen(["btccorehandler/run_terminal"])
elif args.info:
    # runs the clientRPC and calls info
    if server_on:
        server_status = clientRPC.get_server_info()
        print(server_status)
elif args.start:
    # checks with clientRPC if daemon is running then starts server
    if not server_on:
        print("handler server starting")
        subprocess.Popen(["btccorehandler/run_server"])
    else:
        print("Server is already running. Use: 'server -i' to check the status")
elif args.stop:
    # checks with clientRPC if daemon is running then stops server
    if server_on:
        print("handler server stopping")
        clientRPC.server_stop()
    else:
        print("Server is not running. You have to start it first")